web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ../currency-converter:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  image: php:7-fpm
  volumes:
    - ../currency-converter:/code